In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv(r"C:\Users\Madhu\dataset\archive\amazon_reviews.csv")

In [8]:
df.head()

,id,dateAdded,dateUpdated,name,asins,brand,categories,primaryCategories,imageURLs,keys,...,reviews.didPurchase,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.username,sourceURLs
0,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,3,https://www.amazon.com/product-reviews/B00QWO9...,I order 3 of them and one of the item is bad q...,... 3 of them and one of the item is bad quali...,Byger yang,"https://www.barcodable.com/upc/841710106442,ht..."
1,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,4,https://www.amazon.com/product-reviews/B00QWO9...,Bulk is always the less expensive way to go fo...,... always the less expensive way to go for pr...,ByMG,"https://www.barcodable.com/upc/841710106442,ht..."
2,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,5,https://www.amazon.com/product-reviews/B00QWO9...,Well they are not Duracell but for the price i...,... are not Duracell but for the price i am ha...,BySharon Lambert,"https://www.barcodable.com/upc/841710106442,ht..."
3,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,5,https://www.amazon.com/product-reviews/B00QWO9...,Seem to work as well as name brand batteries a...,... as well as name brand batteries at a much ...,Bymark sexson,"https://www.barcodable.com/upc/841710106442,ht..."
4,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,5,https://www.amazon.com/product-reviews/B00QWO9...,These batteries are very long lasting the pric...,... batteries are very long lasting the price ...,Bylinda,"https://www.barcodable.com/upc/841710106442,ht..."

In [9]:
df.columns.tolist()

['id',
 'dateAdded',
 'dateUpdated',
 'name',
 'asins',
 'brand',
 'categories',
 'primaryCategories',
 'imageURLs',
 'keys',
 'manufacturer',
 'manufacturerNumber',
 'reviews.date',
 'reviews.dateSeen',
 'reviews.didPurchase',
 'reviews.doRecommend',
 'reviews.id',
 'reviews.numHelpful',
 'reviews.rating',
 'reviews.sourceURLs',
 'reviews.text',
 'reviews.title',
 'reviews.username',
 'sourceURLs']

In [10]:
df[["reviews.text", "reviews.rating"]].head()

                                        reviews.text  reviews.rating
0  I order 3 of them and one of the item is bad q...               3
1  Bulk is always the less expensive way to go fo...               4
2  Well they are not Duracell but for the price i...               5
3  Seem to work as well as name brand batteries a...               5
4  These batteries are very long lasting the pric...               5

In [11]:
def get_sentiment(rating):
    if rating >= 4:
        return "Positive"
    elif rating == 3:
        return "Neutral"
    else:
        return "Negative"

df["Sentiment"] = df["reviews.rating"].apply(get_sentiment)

In [12]:
df[["reviews.text", "reviews.rating", "Sentiment"]].head()

                                        reviews.text  reviews.rating Sentiment
0  I order 3 of them and one of the item is bad q...               3   Neutral
1  Bulk is always the less expensive way to go fo...               4  Positive
2  Well they are not Duracell but for the price i...               5  Positive
3  Seem to work as well as name brand batteries a...               5  Positive
4  These batteries are very long lasting the pric...               5  Positive

In [13]:
print("Rows and Columns:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df[["reviews.text", "reviews.rating", "Sentiment"]].isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nSentiment Counts:")
print(df["Sentiment"].value_counts())

Rows and Columns: (28332, 25)

Column Names:
['id', 'dateAdded', 'dateUpdated', 'name', 'asins', 'brand', 'categories', 'primaryCategories', 'imageURLs', 'keys', 'manufacturer', 'manufacturerNumber', 'reviews.date', 'reviews.dateSeen', 'reviews.didPurchase', 'reviews.doRecommend', 'reviews.id', 'reviews.numHelpful', 'reviews.rating', 'reviews.sourceURLs', 'reviews.text', 'reviews.title', 'reviews.username', 'sourceURLs', 'Sentiment']

Missing Values:
reviews.text      0
reviews.rating    0
Sentiment         0
dtype: int64

Duplicate Rows:
0

Sentiment Counts:
Sentiment
Positive    25545
Negative     1581
Neutral      1206
Name: count, dtype: int64

In [14]:
df.dropna(subset=["reviews.text", "reviews.rating"], inplace=True)

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
print(df.shape)

(28332, 25)

In [17]:
df["Review"] = df["reviews.text"].astype(str).str.lower()

In [18]:
df["Review"].head()

0    i order 3 of them and one of the item is bad q...
1    bulk is always the less expensive way to go fo...
2    well they are not duracell but for the price i...
3    seem to work as well as name brand batteries a...
4    these batteries are very long lasting the pric...
Name: Review, dtype: object

In [19]:
import re

df["Review"] = df["Review"].apply(
    lambda x: re.sub(r"[^\w\s]", "", x)
)

In [20]:
df["Review"] = df["Review"].str.replace(
    r"\d+", "", regex=True
)

In [21]:
df["Review"] = df["Review"].apply(
    lambda x: re.sub(r"\s+", " ", x).strip()
)

In [22]:
df["Review"].head()

0    i order of them and one of the item is bad qua...
1    bulk is always the less expensive way to go fo...
2    well they are not duracell but for the price i...
3    seem to work as well as name brand batteries a...
4    these batteries are very long lasting the pric...
Name: Review, dtype: object

In [24]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

stop_words = set(ENGLISH_STOP_WORDS)

def preprocess_text(text):
    # Tokenization
    words = text.split()
    
    # Remove stop words
    words = [word for word in words if word not in stop_words]
    
    # Simple lemmatization
    lemmatized_words = []
    
    for word in words:
        if word.endswith("ies"):
            word = word[:-3] + "y"
        elif word.endswith("ing") and len(word) > 5:
            word = word[:-3]
        elif word.endswith("ed") and len(word) > 4:
            word = word[:-2]
        elif word.endswith("s") and not word.endswith("ss") and len(word) > 3:
            word = word[:-1]
        
        lemmatized_words.append(word)
    
    return " ".join(lemmatized_words)

df["Clean_Review"] = df["Review"].apply(preprocess_text)

In [25]:
df[["Review", "Clean_Review"]].head()

,Review,Clean_Review
0,i order of them and one of the item is bad qua...,order item bad quality miss backup spr pcs alu...
1,bulk is always the less expensive way to go fo...,bulk expensive way product like
2,well they are not duracell but for the price i...,duracell price happy
3,seem to work as well as name brand batteries a...,work brand battery better price
4,these batteries are very long lasting the pric...,battery long last price great

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df["Clean_Review"])

print("TF-IDF Matrix Shape:", X.shape)

TF-IDF Matrix Shape: (28332, 5000)

In [27]:
y = df["Sentiment"]

print("Labels prepared successfully!")
print(y.head())

Labels prepared successfully!
0     Neutral
1    Positive
2    Positive
3    Positive
4    Positive
Name: Sentiment, dtype: object

In [28]:
output_path = r"C:\Users\Madhu\dataset\clean_reviews.csv"

df[["Clean_Review", "Sentiment"]].to_csv(
    output_path,
    index=False
)

print("Processed dataset saved successfully!")
print(output_path)

Processed dataset saved successfully!
C:\Users\Madhu\dataset\clean_reviews.csv

In [29]:
print("========== WEEK 2 DATA PREPROCESSING ==========")

print("\nFinal Dataset Shape:")
print(df.shape)

print("\nSentiment Distribution:")
print(df["Sentiment"].value_counts())

print("\nSample Processed Data:")
print(df[["Clean_Review", "Sentiment"]].head())

print("\nTF-IDF Matrix Shape:")
print(X.shape)

print("\nProcessed dataset saved at:")
print(r"C:\Users\Madhu\dataset\clean_reviews.csv")

========== WEEK 2 DATA PREPROCESSING ==========

Final Dataset Shape:
(28332, 27)

Sentiment Distribution:
Sentiment
Positive    25545
Negative     1581
Neutral      1206
Name: count, dtype: int64

Sample Processed Data:
                                        Clean_Review Sentiment
0  order item bad quality miss backup spr pcs alu...   Neutral
1                    bulk expensive way product like  Positive
2                               duracell price happy  Positive
3                    work brand battery better price  Positive
4                      battery long last price great  Positive

TF-IDF Matrix Shape:
(28332, 5000)

Processed dataset saved at:
C:\Users\Madhu\dataset\clean_reviews.csv

In [30]:
import os

print(os.path.exists(r"C:\Users\Madhu\dataset\clean_reviews.csv"))

True

In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Madhu\dataset\clean_reviews.csv")

print("Cleaned dataset loaded successfully!")
print(df.shape)
print(df.columns)
print(df.head())

Cleaned dataset loaded successfully!
(28332, 2)
Index(['Clean_Review', 'Sentiment'], dtype='object')
                                        Clean_Review Sentiment
0  order item bad quality miss backup spr pcs alu...   Neutral
1                    bulk expensive way product like  Positive
2                               duracell price happy  Positive
3                    work brand battery better price  Positive
4                      battery long last price great  Positive

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Replace missing reviews with empty text
df["Clean_Review"] = df["Clean_Review"].fillna("")

# Convert all reviews to strings
df["Clean_Review"] = df["Clean_Review"].astype(str)

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df["Clean_Review"])
y = df["Sentiment"]

print("TF-IDF shape:", X.shape)
print("Labels:")
print(y.value_counts())

TF-IDF shape: (28332, 5000)
Labels:
Sentiment
Positive    25545
Negative     1581
Neutral      1206
Name: count, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 22665
Testing samples: 5667

In [10]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()

nb_model.fit(X_train, y_train)

nb_pred = nb_model.predict(X_test)

print("Naive Bayes model trained successfully!")

Naive Bayes model trained successfully!

In [11]:
from sklearn.metrics import accuracy_score

nb_accuracy = accuracy_score(y_test, nb_pred)

print("Naive Bayes Accuracy:", nb_accuracy)

Naive Bayes Accuracy: 0.9087700723486853

In [12]:
print("Actual values:")
print(y_test.head(10).values)

print("\nPredicted values:")
print(nb_pred[:10])

Actual values:
['Positive' 'Positive' 'Positive' 'Positive' 'Positive' 'Positive'
 'Positive' 'Positive' 'Negative' 'Positive']

Predicted values:
['Positive' 'Positive' 'Positive' 'Positive' 'Positive' 'Positive'
 'Positive' 'Positive' 'Positive' 'Positive']

In [13]:
from sklearn.metrics import accuracy_score

nb_accuracy = accuracy_score(y_test, nb_pred)

print("Naive Bayes Accuracy:", nb_accuracy)

Naive Bayes Accuracy: 0.9087700723486853

In [14]:
from sklearn.metrics import classification_report

print(classification_report(y_test, nb_pred))

              precision    recall  f1-score   support

    Negative       0.87      0.14      0.24       316
     Neutral       0.00      0.00      0.00       241
    Positive       0.91      1.00      0.95      5110

    accuracy                           0.91      5667
   macro avg       0.59      0.38      0.40      5667
weighted avg       0.87      0.91      0.87      5667

In [15]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, nb_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[  45    0  271]
 [   4    0  237]
 [   3    2 5105]]

In [16]:
print("========== WEEK 3 COMPLETE ==========")
print("Model: Naive Bayes")
print("TF-IDF Features:", X.shape[1])
print("Training Samples:", X_train.shape[0])
print("Testing Samples:", X_test.shape[0])
print("Naive Bayes Accuracy:", nb_accuracy)
print("Week 3 completed successfully!")

========== WEEK 3 COMPLETE ==========
Model: Naive Bayes
TF-IDF Features: 5000
Training Samples: 22665
Testing Samples: 5667
Naive Bayes Accuracy: 0.9087700723486853
Week 3 completed successfully!

In [17]:
print("Empty reviews:", (df["Clean_Review"].str.strip() == "").sum())

Empty reviews: 33

In [18]:
print("Sentiment Distribution:")
print(df["Sentiment"].value_counts())

Sentiment Distribution:
Sentiment
Positive    25545
Negative     1581
Neutral      1206
Name: count, dtype: int64

In [19]:
df = df[df["Clean_Review"].str.strip() != ""].copy()

print("Dataset after removing empty reviews:", df.shape)

Dataset after removing empty reviews: (28299, 2)

In [20]:
output_path = r"C:\Users\Madhu\dataset\clean_reviews_v2.csv"

df[["Clean_Review", "Sentiment"]].to_csv(
    output_path,
    index=False
)

print("Improved dataset saved successfully!")
print(output_path)

Improved dataset saved successfully!
C:\Users\Madhu\dataset\clean_reviews_v2.csv

In [21]:
# Week 4 – Text Cleaning and Data Preparation

In [22]:
print("========== WEEK 4 COMPLETE ==========")
print("Final Dataset Shape:", df.shape)
print("Empty Reviews:", (df["Clean_Review"].str.strip() == "").sum())
print("\nSentiment Distribution:")
print(df["Sentiment"].value_counts())
print("\nCleaned dataset saved successfully!")

========== WEEK 4 COMPLETE ==========
Final Dataset Shape: (28299, 2)
Empty Reviews: 0

Sentiment Distribution:
Sentiment
Positive    25516
Negative     1579
Neutral      1204
Name: count, dtype: int64

Cleaned dataset saved successfully!

In [23]:
# Week 5 – Model Training

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df["Clean_Review"])
y = df["Sentiment"]

print("TF-IDF Shape:", X.shape)
print("Labels:")
print(y.value_counts())

TF-IDF Shape: (28299, 5000)
Labels:
Sentiment
Positive    25516
Negative     1579
Neutral      1204
Name: count, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Samples:", X_train.shape[0])
print("Testing Samples:", X_test.shape[0])

Training Samples: 22639
Testing Samples: 5660

In [27]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)

print("Logistic Regression trained successfully!")

Logistic Regression trained successfully!

In [28]:
from sklearn.metrics import accuracy_score

lr_accuracy = accuracy_score(y_test, lr_pred)

print("Logistic Regression Accuracy:", lr_accuracy)

Logistic Regression Accuracy: 0.850530035335689

In [29]:
from sklearn.metrics import classification_report

print("Logistic Regression Classification Report:")
print(classification_report(y_test, lr_pred))

Logistic Regression Classification Report:
              precision    recall  f1-score   support

    Negative       0.50      0.81      0.62       316
     Neutral       0.22      0.61      0.33       241
    Positive       0.98      0.86      0.92      5103

    accuracy                           0.85      5660
   macro avg       0.57      0.76      0.62      5660
weighted avg       0.92      0.85      0.88      5660

In [30]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(
    class_weight="balanced",
    random_state=42
)

svm_model.fit(X_train, y_train)

svm_pred = svm_model.predict(X_test)

print("SVM trained successfully!")

SVM trained successfully!

In [31]:
svm_accuracy = accuracy_score(y_test, svm_pred)

print("SVM Accuracy:", svm_accuracy)

SVM Accuracy: 0.9250883392226148

In [32]:
print("SVM Classification Report:")
print(classification_report(y_test, svm_pred))

SVM Classification Report:
              precision    recall  f1-score   support

    Negative       0.67      0.73      0.70       316
     Neutral       0.41      0.48      0.44       241
    Positive       0.97      0.96      0.96      5103

    accuracy                           0.93      5660
   macro avg       0.69      0.72      0.70      5660
weighted avg       0.93      0.93      0.93      5660

In [33]:
print("========== MODEL COMPARISON ==========")

print("Naive Bayes Accuracy      :", nb_accuracy)
print("Logistic Regression       :", lr_accuracy)
print("SVM Accuracy              :", svm_accuracy)

========== MODEL COMPARISON ==========
Naive Bayes Accuracy      : 0.9087700723486853
Logistic Regression       : 0.850530035335689
SVM Accuracy              : 0.9250883392226148

In [34]:
accuracies = {
    "Naive Bayes": nb_accuracy,
    "Logistic Regression": lr_accuracy,
    "SVM": svm_accuracy
}

best_model = max(accuracies, key=accuracies.get)

print("Best Model:", best_model)
print("Best Accuracy:", accuracies[best_model])

Best Model: SVM
Best Accuracy: 0.9250883392226148

In [49]:
print("======================================")
print("        WEEK 5 COMPLETED")
print("======================================")

print("Naive Bayes Accuracy      :", nb_accuracy)
print("Logistic Regression       :", lr_accuracy)
print("SVM Accuracy              :", svm_accuracy)

print("\nBest Model:", best_model)
print("Best Accuracy:", accuracies[best_model])

print("\nLogistic Regression and SVM training completed successfully!")

======================================
        WEEK 5 COMPLETED
======================================
Naive Bayes Accuracy      : 0.9087700723486853
Logistic Regression       : 0.850530035335689
SVM Accuracy              : 0.9250883392226148

Best Model: SVM
Best Accuracy: 0.9250883392226148

Logistic Regression and SVM training completed successfully!

In [36]:
# Week 6 – Error Analysis and Model Evaluation

In [37]:
from sklearn.metrics import confusion_matrix

svm_cm = confusion_matrix(y_test, svm_pred)

print("SVM Confusion Matrix:")
print(svm_cm)

SVM Confusion Matrix:
[[ 232   24   60]
 [  39  115   87]
 [  73  141 4889]]

In [38]:
print("SVM Classification Report:")
print(classification_report(y_test, svm_pred))

SVM Classification Report:
              precision    recall  f1-score   support

    Negative       0.67      0.73      0.70       316
     Neutral       0.41      0.48      0.44       241
    Positive       0.97      0.96      0.96      5103

    accuracy                           0.93      5660
   macro avg       0.69      0.72      0.70      5660
weighted avg       0.93      0.93      0.93      5660

In [39]:
import pandas as pd

results = pd.DataFrame({
    "Review": df.loc[y_test.index, "Clean_Review"],
    "Actual": y_test,
    "Predicted": svm_pred
})

errors = results[results["Actual"] != results["Predicted"]]

print("Total incorrect predictions:", len(errors))
print("\nSample errors:")
print(errors.head(10))

Total incorrect predictions: 424

Sample errors:
                                                  Review    Actual Predicted
13481  need basic tablet work fall apart compar ipad ...  Negative  Positive
22     long duracell battery xbox controller explod l...  Positive  Negative
24183  year old boy broke month bumper guard wont pow...  Negative   Neutral
7797        lot battery didnt work maybe just experience  Negative   Neutral
22399  hii order daughter extensive lik tablet didnt ...  Negative  Positive
23359  kid love product parental restriction set know...  Positive   Neutral
6793   great load extra battery children use battery ...  Positive   Neutral
22281                         daughter tablet month work   Neutral  Positive
24473                       got son till timer shut love  Positive   Neutral
12602  research buy tap upgrad version voice activat ...  Negative   Neutral

In [40]:
print("Actual vs Predicted:")
print(pd.crosstab(
    results["Actual"],
    results["Predicted"]
))

Actual vs Predicted:
Predicted  Negative  Neutral  Positive
Actual
Negative        232       24        60
Neutral          39      115        87
Positive         73      141      4889

In [41]:
svm_error = 1 - svm_accuracy

print("SVM Accuracy:", svm_accuracy)
print("SVM Error Rate:", svm_error)

SVM Accuracy: 0.9250883392226148
SVM Error Rate: 0.0749116607773852

## Limitations

- The dataset contains many more positive reviews than negative and neutral reviews.
- Some reviews may contain unclear or mixed opinions.
- Sarcasm and context can be difficult to classify.
- The model depends on the quality of the training data.
- The system currently works mainly with text reviews.

In [46]:
print("======================================")
print("        WEEK 6 COMPLETED")
print("======================================")
print("Best Model: SVM")
print("SVM Accuracy:", svm_accuracy)
print("Incorrect Predictions:", len(errors))
print("Error Analysis Completed Successfully!")

======================================
        WEEK 6 COMPLETED
======================================
Best Model: SVM
SVM Accuracy: 0.9250883392226148
Incorrect Predictions: 424
Error Analysis Completed Successfully!